name: studbud
description: A Flutter project replicating StudBud UI from Figma screenshots.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
